### PR TITLE
Update 2-setup-azure-environment.yml

### PR DESCRIPTION
**Pull request by shearpaladin**
Updated Lines:
86: 'env' -> 'with'
92: 'env' -> 'with'
98: 'env' -> 'with'

GitHub Actions kept failing on this step

Updated Line:
110: ./.github/script/initialize-repository.sh

Using the correct script path because pull-main.sh does not exist

### Summary

#47

### Changes

Fixes Github Actions Step 2 Failure. 
Changed 'env' - > 'with'
Updated file path to correct script

### Task list

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by shearpaladin** [comment]
@heiskr 
I've created a pull request to solve the issues found in Step 2. 

(This is my first PR on something public so I'd like some feedback too 👍 )

**Comment by shearpaladin** [comment]
Update: this issue is on Multiple steps.. it seems i see it on step 3.. we have to change all the paths

**Comment by shearpaladin** [comment]
Changed the file name to pull-main.sh

**Comment by shearpaladin** [comment]
> Thank you for the pull request. Can we keep the env->with for this one, and a separate one to address scripts?
> 
> Thanks ✨

Yes for sure!

**Comment by shearpaladin** [comment]
Okay, it should be changed with only 'with'.

I'll create a separate PR for scripts

**Review by heiskr — APPROVED** [review]

**Comment by heiskr** [comment]
Thank you :)

**Pull request merged**
