### PR TITLE
Rename initialize-repository.sh to pull-main.sh

### PR DESCRIPTION
**Pull request by shearpaladin**
Let's rename this file to pull-main. So it makes more sense in the script it's calling from

### Summary

In the workflows folder, we call the pull-main script but it does not exist. I checked the script files and its name as 
initialize-repository.sh making each of the workflow steps fail since it is referenced as pull-main.sh on each of them.

      # Pull main.
      - name: Pull main
        run: ./.github/script/pull-main.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }

### Changes

renamed script from `initialize-repository.sh` -> `pull-main.sh`

### Task list

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by shearpaladin** [comment]
@heiskr Fix to script path

**Comment by shearpaladin** [comment]
#38 is a duplicate of this issue

**Comment by shearpaladin** [comment]
@heiskr I believe this might be the best approach without changing all the other workflow files.

**Review by heiskr — APPROVED** [review]

**Comment by shearpaladin** [comment]
Nevermind about these changes @heiskr I see the rest of the steps have references to initialize-repository.sh

**Pull request closed without merging**
